package microdbCommon

const (
	SHOW_DBS         = "SHOW_DBS"
	SHOW_TABLES      = "SHOW_TABLES"
	USE_DB           = "USE_DB"
	CREATE_DB        = "CREATE_DB"
	CREATE_TABLE     = "CREATE_TABLE"
	DB_EXISTS_USE_DB = "DB_EXISTS_USE_DB"
	DB_EXISTS        = "DB_EXISTS"
	DROP_DB          = "DROP_DB"
	DROP_TABLE       = "DROP_TABLE"
	DESC_TABLE       = "DESC_TABLE"
	SAVE_RECORD      = "SAVE_RECORD"
	CLIENT_VERSION   = "CLIENT_VERSION"
	SERVER_VERSION   = "SERVER_VERSION"
)
